apiVersion: v1
kind: Service
metadata:
  name: nurseada-cdss
  labels:
    app: nurseada-cdss
spec:
  type: {{ .Values.cdss.service.type }}
  selector:
    app: nurseada-cdss
  ports:
    - port: {{ .Values.cdss.service.port }}
      targetPort: 8002
      protocol: TCP
      name: http

