apiVersion: v1
kind: Service
metadata:
  name: nurseada-gateway
  labels:
    app: nurseada-gateway
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app: nurseada-gateway
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http

