from __future__ import annotations

import re
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "drsmfhkgwohtbyhfpxqu" / "supabase" / "migrations" / "20260320131000_medical_knowledge_seed.sql"
sys.path.insert(0, str(ROOT / "services" / "knowledge"))

from app.clinical_content import DIABETES_CONTENT, DKA_CONTENT
from app.herbal_content import DRUG_HERB_INTERACTIONS, HERBAL_CONTENT


def q(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def qarr(values: list[str]) -> str:
    escaped = ", ".join(q(v) for v in values)
    return f"ARRAY[{escaped}]::text[]"


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return re.sub(r"-{2,}", "-", slug)


def parse_remedy_name(text: str) -> str:
    if "**" in text:
        parts = text.split("**")
        if len(parts) > 2:
            return parts[1].split(":")[0].strip()
    return text.split(":")[0].strip()[:80]


def parse_scientific_name(text: str) -> str:
    match = re.search(r"\(([A-Z][a-z]+(?:\s+[a-z][a-z\-]+)+)\)", text)
    return match.group(1).strip() if match else ""


def parse_local_names(text: str) -> list[str]:
    if "–" not in text:
        return []
    snippet = text.split("–", 1)[1].split(":", 1)[0].strip()
    matches = re.findall(r"([A-Za-z][A-Za-z\s'/-]+?)\s*\([A-Za-z]+\)", snippet)
    return [m.strip() for m in matches if m.strip()]


def mk_topic(keywords: list[str]) -> str:
    for k in ("dka", "ketone", "diabetes"):
        if any(k in kw for kw in keywords):
            if k == "ketone":
                return "ketones"
            return k
    return "general"


def build_sql() -> str:
    lines: list[str] = []
    lines.append("-- Generated by scripts/generate_medical_knowledge_seed.py")
    lines.append("-- Seeds medical and herbal knowledge from current Python content.")
    lines.append("")

    lines.append("insert into medical_knowledge_chunks")
    lines.append("(slug, title, topic, locale, text, source, keywords, is_active)")
    lines.append("values")
    clinical_rows: list[str] = []
    for idx, chunk in enumerate(DKA_CONTENT + DIABETES_CONTENT, start=1):
        title = chunk.source
        slug = slugify(f"{mk_topic(chunk.keywords)}-{idx}-{title}")[:120]
        clinical_rows.append(
            f"  ({q(slug)}, {q(title)}, {q(mk_topic(chunk.keywords))}, 'en', {q(chunk.text)}, {q(chunk.source)}, {qarr(chunk.keywords)}, true)"
        )
    lines.append(",\n".join(clinical_rows) + ";")
    lines.append("")

    lines.append("insert into herbal_remedies")
    lines.append(
        "(slug, name, scientific_name, local_names, locale, condition, text, source, evidence_level, contraindications, drug_interactions, blocked_populations, keywords, is_active)"
    )
    lines.append("values")
    herbal_rows: list[str] = []
    seen: dict[str, int] = {}
    for chunk in HERBAL_CONTENT:
        name = parse_remedy_name(chunk.text)
        scientific_name = parse_scientific_name(chunk.text)
        local_names = parse_local_names(chunk.text)
        base_slug = slugify(f"{chunk.condition}-{name}")[:100]
        seen[base_slug] = seen.get(base_slug, 0) + 1
        slug = base_slug if seen[base_slug] == 1 else f"{base_slug}-{seen[base_slug]}"
        herbal_rows.append(
            "  ("
            + ", ".join(
                [
                    q(slug),
                    q(name),
                    (q(scientific_name) if scientific_name else "null"),
                    qarr(local_names),
                    "'en'",
                    q(chunk.condition),
                    q(chunk.text),
                    q(chunk.source),
                    q(chunk.evidence_level),
                    qarr(chunk.contraindications),
                    qarr(chunk.drug_interactions),
                    qarr(chunk.blocked_populations),
                    qarr(chunk.keywords),
                    "true",
                ]
            )
            + ")"
        )
    lines.append(",\n".join(herbal_rows) + ";")
    lines.append("")

    lines.append("insert into herbal_drug_interaction_rules")
    lines.append("(herb_keywords, drug_keywords, severity, message_template, source, locale, is_active)")
    lines.append("values")
    interaction_rows: list[str] = []
    for herbs, drugs, severity, template in DRUG_HERB_INTERACTIONS:
        interaction_rows.append(
            f"  ({qarr(herbs)}, {qarr(drugs)}, {q(severity)}, {q(template)}, 'interaction-table', 'en', true)"
        )
    lines.append(",\n".join(interaction_rows) + ";")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    OUT.write_text(build_sql(), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
